package org.springframework.samples.flatbook.utils.assertj;

import org.assertj.core.api.AbstractObjectAssert;
import org.springframework.samples.flatbook.model.Indicators;

/**
 * Abstract base class for {@link Indicators} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractIndicatorsAssert<S extends AbstractIndicatorsAssert<S, A>, A extends Indicators> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractIndicatorsAssert}</code> to make assertions on actual Indicators.
   * @param actual the Indicators we want to make assertions on.
   */
  protected AbstractIndicatorsAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
