package org.springframework.samples.flatbook.util.assertj;

import org.springframework.samples.flatbook.model.Advertisement;

/**
 * {@link Advertisement} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractAdvertisementAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class AdvertisementAssert extends AbstractAdvertisementAssert<AdvertisementAssert, Advertisement> {

  /**
   * Creates a new <code>{@link AdvertisementAssert}</code> to make assertions on actual Advertisement.
   * @param actual the Advertisement we want to make assertions on.
   */
  public AdvertisementAssert(Advertisement actual) {
    super(actual, AdvertisementAssert.class);
  }

  /**
   * An entry point for AdvertisementAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myAdvertisement)</code> and get specific assertion with code completion.
   * @param actual the Advertisement we want to make assertions on.
   * @return a new <code>{@link AdvertisementAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static AdvertisementAssert assertThat(Advertisement actual) {
    return new AdvertisementAssert(actual);
  }
}
