package org.springframework.samples.flatbook.utils.assertj;

import org.springframework.samples.flatbook.model.dtos.AdvertisementForm;

/**
 * {@link AdvertisementForm} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractAdvertisementFormAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class AdvertisementFormAssert extends AbstractAdvertisementFormAssert<AdvertisementFormAssert, AdvertisementForm> {

  /**
   * Creates a new <code>{@link AdvertisementFormAssert}</code> to make assertions on actual AdvertisementForm.
   * @param actual the AdvertisementForm we want to make assertions on.
   */
  public AdvertisementFormAssert(AdvertisementForm actual) {
    super(actual, AdvertisementFormAssert.class);
  }

  /**
   * An entry point for AdvertisementFormAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myAdvertisementForm)</code> and get specific assertion with code completion.
   * @param actual the AdvertisementForm we want to make assertions on.
   * @return a new <code>{@link AdvertisementFormAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static AdvertisementFormAssert assertThat(AdvertisementForm actual) {
    return new AdvertisementFormAssert(actual);
  }
}
