package org.springframework.samples.flatbook.utils.assertj;

import org.springframework.samples.flatbook.model.Host;

/**
 * {@link Host} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractHostAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class HostAssert extends AbstractHostAssert<HostAssert, Host> {

  /**
   * Creates a new <code>{@link HostAssert}</code> to make assertions on actual Host.
   * @param actual the Host we want to make assertions on.
   */
  public HostAssert(Host actual) {
    super(actual, HostAssert.class);
  }

  /**
   * An entry point for HostAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myHost)</code> and get specific assertion with code completion.
   * @param actual the Host we want to make assertions on.
   * @return a new <code>{@link HostAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static HostAssert assertThat(Host actual) {
    return new HostAssert(actual);
  }
}
