package org.springframework.samples.flatbook.utils.assertj;

import org.springframework.samples.flatbook.model.Review;

/**
 * {@link Review} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractReviewAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class ReviewAssert extends AbstractReviewAssert<ReviewAssert, Review> {

  /**
   * Creates a new <code>{@link ReviewAssert}</code> to make assertions on actual Review.
   * @param actual the Review we want to make assertions on.
   */
  public ReviewAssert(Review actual) {
    super(actual, ReviewAssert.class);
  }

  /**
   * An entry point for ReviewAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myReview)</code> and get specific assertion with code completion.
   * @param actual the Review we want to make assertions on.
   * @return a new <code>{@link ReviewAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static ReviewAssert assertThat(Review actual) {
    return new ReviewAssert(actual);
  }
}
