package org.springframework.samples.flatbook.utils.assertj;

import org.springframework.samples.flatbook.model.Task;

/**
 * {@link Task} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractTaskAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class TaskAssert extends AbstractTaskAssert<TaskAssert, Task> {

  /**
   * Creates a new <code>{@link TaskAssert}</code> to make assertions on actual Task.
   * @param actual the Task we want to make assertions on.
   */
  public TaskAssert(Task actual) {
    super(actual, TaskAssert.class);
  }

  /**
   * An entry point for TaskAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myTask)</code> and get specific assertion with code completion.
   * @param actual the Task we want to make assertions on.
   * @return a new <code>{@link TaskAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static TaskAssert assertThat(Task actual) {
    return new TaskAssert(actual);
  }
}
