package org.springframework.samples.flatbook.utils.assertj;

import org.springframework.samples.flatbook.model.Tenant;

/**
 * {@link Tenant} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractTenantAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class TenantAssert extends AbstractTenantAssert<TenantAssert, Tenant> {

  /**
   * Creates a new <code>{@link TenantAssert}</code> to make assertions on actual Tenant.
   * @param actual the Tenant we want to make assertions on.
   */
  public TenantAssert(Tenant actual) {
    super(actual, TenantAssert.class);
  }

  /**
   * An entry point for TenantAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myTenant)</code> and get specific assertion with code completion.
   * @param actual the Tenant we want to make assertions on.
   * @return a new <code>{@link TenantAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static TenantAssert assertThat(Tenant actual) {
    return new TenantAssert(actual);
  }
}
