package org.springframework.samples.flatbook.util.assertj;

import org.springframework.samples.flatbook.model.FlatReview;

/**
 * {@link FlatReview} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractFlatReviewAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class FlatReviewAssert extends AbstractFlatReviewAssert<FlatReviewAssert, FlatReview> {

  /**
   * Creates a new <code>{@link FlatReviewAssert}</code> to make assertions on actual FlatReview.
   * @param actual the FlatReview we want to make assertions on.
   */
  public FlatReviewAssert(FlatReview actual) {
    super(actual, FlatReviewAssert.class);
  }

  /**
   * An entry point for FlatReviewAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myFlatReview)</code> and get specific assertion with code completion.
   * @param actual the FlatReview we want to make assertions on.
   * @return a new <code>{@link FlatReviewAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static FlatReviewAssert assertThat(FlatReview actual) {
    return new FlatReviewAssert(actual);
  }
}
